export const COUNTRY_NAMES = {
  "HK": "Hong Kong",
  "UA": "Ukraine",
  "PL": "Poland",
  "FR": "France",
  "ES": "Spain",
  "DE": "Germany",
  "GB": "United Kingdom",
  "IE": "Ireland",
  "PT": "Portugal",
  "IT": "Italy",
  "AT": "Austria",
  "CH": "Switzerland",
  "BE": "Belgium",
  "NL": "Netherlands",
  "LU": "Luxembourg",
  "DK": "Denmark",
  "SE": "Sweden",
  "NO": "Norway",
  "FI": "Finland",
  "IS": "Iceland",
  "CZ": "Czech Republic",
  "SK": "Slovakia",
  "HU": "Hungary",
  "RO": "Romania",
  "BG": "Bulgaria",
  "HR": "Croatia",
  "SI": "Slovenia",
  "RS": "Serbia",
  "BA": "Bosnia and Herzegovina",
  "ME": "Montenegro",
  "MK": "North Macedonia",
  "AL": "Albania",
  "GR": "Greece",
  "LT": "Lithuania",
  "LV": "Latvia",
  "EE": "Estonia",
  "MD": "Moldova",
  "CY": "Cyprus",
  "MT": "Malta",
  "XK": "Kosovo",
  "TR": "Turkey",
  "AD": "Andorra",
  "LI": "Liechtenstein",
  "MC": "Monaco",
  "SM": "San Marino",
  "VA": "Vatican City",
  "US": "USA",
  "CA": "Canada",
  "RU": "Russia",
  "BY": "Belarus",
  "GE": "Georgia",
  "AM": "Armenia",
  "AZ": "Azerbaijan",
  "BR": "Brazil",
  "AU": "Australia",
  "NZ": "New Zealand",
  "JP": "Japan",
  "ZA": "South Africa",
  "KR": "South Korea",
  "CL": "Chile",
  "AR": "Argentina",
  "TW": "Taiwan",
  "IR": "Iran",
  "AE": "United Arab Emirates",
  "OM": "Oman",
  "UZ": "Uzbekistan",
  "IN": "India",
  "ID": "Indonesia",
  "CN": "China",
  "IQ": "Iraq",
  "SA": "Saudi Arabia",
  "KZ": "Kazakhstan",
  "TM": "Turkmenistan",
  "SG": "Singapore",
  "QA": "Qatar",
  "IL": "Israel",
  "KG": "Kyrgyzstan",
  "MY": "Malaysia",
  "MN": "Mongolia",
  "KW": "Kuwait",
  "TH": "Thailand",
  "JO": "Jordan",
  "VN": "Vietnam",
  "PH": "Philippines",
  "NP": "Nepal",
  "BH": "Bahrain",
  "MM": "Myanmar",
  "SY": "Syria",
  "LK": "Sri Lanka",
  "KH": "Cambodia",
  "BN": "Brunei",
  "BD": "Bangladesh",
  "LB": "Lebanon",
  "PK": "Pakistan",
  "TJ": "Tajikistan",
  "CO": "Colombia",
  "EC": "Ecuador",
  "UY": "Uruguay",
  "PE": "Peru",
  "BO": "Bolivia",
  "VE": "Venezuela",
  "PY": "Paraguay",
  "MX": "Mexico",
  "SV": "El Salvador",
  "CU": "Cuba",
  "GT": "Guatemala",
  "PA": "Panama",
  "CR": "Costa Rica",
  "TT": "Trinidad and Tobago",
  "EG": "Egypt",
  "DZ": "Algeria",
  "MA": "Morocco",
  "MU": "Mauritius",
  "AO": "Angola",
  "CI": "Ivory Coast",
  "TN": "Tunisia",
  "RW": "Rwanda",
  "UG": "Uganda",
  "KE": "Kenya",
  "SN": "Senegal",
  "BW": "Botswana",
  "NA": "Namibia",
  "TZ": "United Republic of Tanzania",
  "PG": "Papua New Guinea",
  "PS": "Palestine",
};
