export const COUNTRY_NAMES = {
  "UA": "Ukraine",
  "PL": "Poland",
  "FR": "France",
  "ES": "Spain",
  "DE": "Germany",
  "GB": "United Kingdom",
  "IE": "Ireland",
  "PT": "Portugal",
  "IT": "Italy",
  "AT": "Austria",
  "CH": "Switzerland",
  "BE": "Belgium",
  "NL": "Netherlands",
  "LU": "Luxembourg",
  "DK": "Denmark",
  "SE": "Sweden",
  "NO": "Norway",
  "FI": "Finland",
  "IS": "Iceland",
  "CZ": "Czech Republic",
  "SK": "Slovakia",
  "HU": "Hungary",
  "RO": "Romania",
  "BG": "Bulgaria",
  "HR": "Croatia",
  "SI": "Slovenia",
  "RS": "Serbia",
  "BA": "Bosnia and Herzegovina",
  "ME": "Montenegro",
  "MK": "North Macedonia",
  "AL": "Albania",
  "GR": "Greece",
  "LT": "Lithuania",
  "LV": "Latvia",
  "EE": "Estonia",
  "MD": "Moldova",
  "CY": "Cyprus",
  "MT": "Malta",
  "XK": "Kosovo",
  "TR": "Turkey",
  "AD": "Andorra",
  "LI": "Liechtenstein",
  "MC": "Monaco",
  "SM": "San Marino",
  "VA": "Vatican City",
  "US": "USA",
  "CA": "Canada",
  "RU": "Russia",
  "BY": "Belarus",
  "GE": "Georgia",
  "AM": "Armenia",
  "AZ": "Azerbaijan"
};
