export const DRIVER_COPY = {
  ru: {
    drive: "Поездка",
    offline: "Офлайн-карты и камеры",
    unit: "км/ч",
    limit: "ЛИМИТ",
    clear: "✓ Впереди всё спокойно",
    active: "Защита активна",
    idle: "Готовы к поездке",
    gps: "Ожидание GPS",
    heading: "Определяем направление",
    camera: "Камера скорости",
    red: "Камера красного света",
    mobile: "Мобильный контроль",
    average: "Контроль средней скорости",
    averageValue: "Средняя",
    remaining: "Осталось",
    slow: "Снизьте скорость",
    through: "Камера через",
    download: "Скачать",
    update: "Обновить",
    saved: "✓ Загружено",
    today: "Обновлено сегодня",
    updated: "Обновлено",
    sizeUnknown: "Размер уточняется",
    maps: "Камеры и предупреждения работают офлайн. Карта загружается через интернет.",
    add: "Добавить",
    position: "Используем ваше текущее местоположение",
    noPosition: "Включите поездку, чтобы определить местоположение",
    background: "Предупреждения при выключенном экране",
    settings: "Настройки",
    meters: "м",
    km: "км",
  },
  uk: {
    drive: "Поїздка",
    offline: "Офлайн-карти та камери",
    unit: "км/год",
    limit: "ЛІМІТ",
    clear: "✓ Попереду все спокійно",
    active: "Захист активний",
    idle: "Готові до поїздки",
    gps: "Очікування GPS",
    heading: "Визначаємо напрямок",
    camera: "Камера швидкості",
    red: "Камера червоного світла",
    mobile: "Мобільний контроль",
    average: "Контроль середньої швидкості",
    averageValue: "Середня",
    remaining: "Залишилось",
    slow: "Знизьте швидкість",
    through: "Камера через",
    download: "Завантажити",
    update: "Оновити",
    saved: "✓ Завантажено",
    today: "Оновлено сьогодні",
    updated: "Оновлено",
    sizeUnknown: "Розмір уточнюється",
    maps: "Камери й попередження працюють офлайн. Карта завантажується через інтернет.",
    add: "Додати",
    position: "Використовуємо ваше поточне місцеположення",
    noPosition: "Увімкніть поїздку, щоб визначити місцеположення",
    background: "Попередження з вимкненим екраном",
    settings: "Налаштування",
    meters: "м",
    km: "км",
  },
  en: {
    drive: "Drive",
    offline: "Offline maps & cameras",
    unit: "km/h",
    limit: "LIMIT",
    clear: "✓ All clear ahead",
    active: "Protection active",
    idle: "Ready to drive",
    gps: "Waiting for GPS",
    heading: "Finding your direction",
    camera: "Speed camera",
    red: "Red-light camera",
    mobile: "Mobile control",
    average: "Average-speed control",
    averageValue: "Average",
    remaining: "Remaining",
    slow: "Reduce your speed",
    through: "Camera in",
    download: "Download",
    update: "Update",
    saved: "✓ Downloaded",
    today: "Updated today",
    updated: "Updated",
    sizeUnknown: "Size pending",
    maps: "Cameras and alerts work offline. The map loads using internet.",
    add: "Add",
    position: "Using your current location",
    noPosition: "Start driving mode to find your location",
    background: "Alerts with the screen off",
    settings: "Settings",
    meters: "m",
    km: "km",
  },
  pl: {
    drive: "Jazda",
    offline: "Mapy i fotoradary offline",
    unit: "km/h",
    limit: "LIMIT",
    clear: "✓ Przed tobą spokojnie",
    active: "Ochrona aktywna",
    idle: "Gotowy do jazdy",
    gps: "Oczekiwanie na GPS",
    heading: "Ustalamy kierunek",
    camera: "Fotoradar",
    red: "Kontrola czerwonego światła",
    mobile: "Kontrola mobilna",
    average: "Odcinkowy pomiar prędkości",
    averageValue: "Średnia",
    remaining: "Pozostało",
    slow: "Zwolnij",
    through: "Fotoradar za",
    download: "Pobierz",
    update: "Aktualizuj",
    saved: "✓ Pobrano",
    today: "Zaktualizowano dzisiaj",
    updated: "Zaktualizowano",
    sizeUnknown: "Rozmiar oczekuje",
    maps: "Fotoradary i ostrzeżenia działają offline. Mapa wymaga internetu.",
    add: "Dodaj",
    position: "Używamy twojej bieżącej lokalizacji",
    noPosition: "Rozpocznij jazdę, aby ustalić lokalizację",
    background: "Ostrzeżenia przy wyłączonym ekranie",
    settings: "Ustawienia",
    meters: "m",
    km: "km",
  },
};
export function drivingLabel(point, copy) {
  return (
    {
      red_light_camera: copy.red,
      mobile_control: copy.mobile,
      average_speed_start: copy.average,
      average_speed_end: copy.average,
    }[point?.type] || copy.camera
  );
}
