/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3f8345ade629d855e85ac2cc4befa0ac)
interface __BaseEnv_Env {
	CAMERA_DATA: R2Bucket;
	DOWNLOAD_SIGNING_SECRET: string;
	DOWNLOAD_LIMITER: DurableObjectNamespace<import("./worker").DownloadLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "DownloadLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DOWNLOAD_SIGNING_SECRET">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}